-- Make a file containing the SQL statements that 
-- create your entire database schema, named dbDDL.sql. 
-- This includes the tables with their constraints, 
-- view, indexes, triggers, and all other database 
-- objects if you have them.
-- To keep the project consistent, make sure you 
-- have at least 8 tables. Make sure you have at 
-- least 2 database objects among trigger, function, 
-- procedure or view.